### ISSUE TITLE
Issues with state store/promises

### ISSUE THREAD

**Issue by sardine-craft** [PathfinderHonorManager/PathfinderHonorManagerUI#7]
I'm really new to pinia, typescript, and vue apps, so I don't really know how I should be approaching this problem. The issue, I think, is with my state store or my fetch handler file. I want to be able to quickly resolve a promise for the API response so that I can work with the new data returned, but I haven't found anything useful in vue or pinia docs.
The files I've been dealing with here are:
fetchHandler.ts - fetch handler
pathfinders.ts - state store
honors.ts - state store
The code can be found on the [develop-vue3](https://github.com/PathfinderHonorManager/PathfinderHonorManagerUI/tree/develop-vue3) branch

**Comment by johnmberger** [comment]
@sardine-craft, I can open a pull request with an example if you give me write access to this repo :)
